# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pinYin', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 's_brand',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 's_letter',
            },
        ),
        migrations.CreateModel(
            name='Outer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 's_outer',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=50, verbose_name='口令')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=12, verbose_name='电话')),
                ('img', models.ImageField(upload_to='user/images', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 's_user',
            },
        ),
    ]
