# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='pinYin',
            new_name='url',
        ),
    ]
