# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20180719_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chexi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pinpai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Letter')),
            ],
            options={
                'db_table': 's_pinpai',
            },
        ),
        migrations.AddField(
            model_name='chexi',
            name='pinpai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Pinpai'),
        ),
    ]
