# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20180719_2127'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chexi',
            table='s_chexi',
        ),
    ]
